image: node:latest

stages:
  - deploy

# Ref: https://docs.gitlab.com/ee/ci/caching/#cache-nodejs-dependencies
cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  # TODO remove force when peer dependency issues are sorted
  - npm ci --cache .npm --prefer-offline --force

# Ref: https://docs.gitlab.com/ee/user/project/pages/getting_started/pages_from_scratch.html
pages:
  stage: deploy
  script:
    - npm run check
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
